### PR TITLE
update to webpack 4

### LINKED ISSUE #86: Webpack 4 deprecation warning
Hi
I have this warning
```
(node:3792) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
Modules
```
"assets-webpack-plugin": "^3.5.1",
"webpack": "^4.1.1",
```
Thank you

### PR DESCRIPTION
**Pull request by ztoben**
* Upgrades to webpack 4
* Fixes #86 and #85 
* Chunk ids can now be alphanumeric namedChunks (s/o @saveman71)
* Bumps quite a few dependencies
* Common chunks is no longer in webpack, remove tests around this
* `extract-text-webpack-plugin` does not support webpack@4 and suggests switching to `mini-css-extract-plugin` instead, if you want a test for this to check support I could add one

Very quickly put together just to get rid of the deprecation warning in our console after upgrading to webpack 4. Let me know if I missed anything.

### CODE REVIEW

**Comment by ztoben** [comment]
Tested this by pulling down my forked version and running locally and everything is working, including `mini-css-extract-plugin`.

**Comment by ztoben** [comment]
AppVeyor seems to fail due to the node version being used I think? Without running the files through babel or something I think the easiest solution would just be to build on the latest LTS of node, the tests pass locally for me on node@8.9.4.

**Comment by ztoben** [comment]
Tested this by pulling down my forked version and running locally and everything is working, including `mini-css-extract-plugin`.

AppVeyor seems to fail due to the node version being used. Without running the files through babel I think the easiest solution would just be to build on the latest LTS of node, the tests pass locally for me on node@8.9.4.

Edit: Okay, updated appveyor and travis to use node 8. Took a few guess and check commits 😉

**Review by SebastiaanNijland — APPROVED** [review]

**Comment by saveman71** [comment]
@ztoben Do you think you could fix #85 in this PR as well?

Thank you for the work already done here!

EDIT: Did it myself, see https://github.com/saveman71/assets-webpack-plugin
**EDIT 2: Changes were merged here!**

**Comment by ztoben** [comment]
@kossnocorp, any chance you could take a look at this?

**Comment by ducdigital** [comment]
Wondering when will this get merged?

**Comment by kossnocorp** [comment]
@ztoben @saveman71 @SebastiaanNijland thank you, guys! This PR was published as `assets-webpack-plugin@3.6.0`.

Any chance that some of you want to help me maintain the package? My priorities have shifted, and nowadays I'm entirely focused on my own business and date-fns. I would appreciate the help as the package obviously needs some love.

**Comment by ztoben** [comment]
@kossnocorp, I'd be happy to help maintain it. I use it at work and get some time there to work on projects like these.

**Comment by kossnocorp** [comment]
@ztoben great, thanks! I've added you as collaborators to the repo. What's your npm username?

**Comment by ztoben** [comment]
@kossnocorp, the same as my github handle.

**Comment by kossnocorp** [comment]
@ztoben ✅

**Comment by stoikerty** [comment]
Thanks for helping us out with this @kossnocorp!

**Comment by kossnocorp** [comment]
@saveman71 and everyone else: ❤️ thank you for your patience 🙏

**Pull request merged**
