### PR TITLE
add includeManifest option fix #43

### LINKED ISSUE #43: get manifest.json key inside index.html
hey,

i'm having a static `index.html` (not generated by webpack)

inside it i would like to include one of entries declared in webpack 

```
    entry: {
        admin: './assets/admin/index.js',
        app: './assets/app/index.js',
        vendor: ['jquery', 'd3']
    }
```

the `manifest.json` is generated, but i have no ideea how i could parse html on each build and push targeted entry.

any ideea about what plugin could parse `index.html` and write out from `manifest.json` ?

### PR DESCRIPTION
**Pull request by mattkrick**
Closed the other PR prematurely when i saw `entries` is a thing now, sorry bout that!

Inlining a manifest in your html is a best practice for handling long-term cached assets (ie when a chunk goes stale, just get that chunk, not that chunk + the vendor chunk).

This is pretty well discussed in: webpack/webpack#1315
And in a bit friendlier context here (about half way down): https://medium.com/@matt.krick/a-production-ready-realtime-saas-with-webpack-7b11ba2fa5b0#.p1vvfr3bm

Currently, to do it requires either running a separate build step, or triggering a dynamic read at runtime:
https://github.com/mattkrick/meatier/blob/master/src/server/createSSR.js#L38

By including this option in AssetsPlugin, we can eliminate the need for a second build step and builds super fast because we don't even have to read from the filesystem, we can read right from the compilation.

Happy to adjust as needed, & thanks for a great package!

### CODE REVIEW

**Comment by jordanh** [comment]
+1 to this. GREAT idea. Love to see this get merged!

**Comment by mattkrick** [comment]
@kossnocorp thoughts? feedback?

**Comment by kossnocorp** [comment]
Great job! I wish to release this PR as `3.5`. Please fix the conficts so I could merge it.

Sorry for the delay.

**Comment by mattkrick** [comment]
@kossnocorp ready for a good ol squash n merge

**Comment by kossnocorp** [comment]
@mattkrick thank you a lot! Your changes were released as `assets-webpack-plugin@3.5.0`.

**Pull request merged**
