### PR TITLE
Add support for source maps when `includeManifest` option is set

### PR DESCRIPTION
**Pull request by th0r**
Now when `devtool: 'sourcemap'` is used with `includeManifest` option plugin throws an error `Could not locate manifest function in source`.

This PR fixes it.

### CODE REVIEW

**Comment by faceyspacey** [comment]
any word on when this will be merged?

**Comment by jordanh** [comment]
As @mattkrick referenced, +1 to getting this merged.

**Comment by maxmilton** [comment]
LGTM!

**Comment by mattkrick** [comment]
@kossnocorp anything i can do to get this merged?

**Comment by jordanh** [comment]
@kossnocorp +1 one to this. It's blocking us...

**Comment by kossnocorp** [comment]
I'm really sorry, I'll try my best to release it as soon as possible.

**Comment by jordanh** [comment]
Danke!

**Comment by kossnocorp** [comment]
Sorry for the delay again. The fix was released as `3.5.1`.

```
⟩ npm publish
+ assets-webpack-plugin@3.5.1
```

**Pull request merged**
